config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: 'users/registrations'}
  root to: "outfits#index"
  resources :users, only: [:show] 
  resources :outfits do
    get "wishlist", on: :collection
    resources :wish_list_items, only: [:create]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart
    attr_reader :items
    attr_reader :total_price
    
    def initialize
        @items = []
        @total_price = 0.0
    end
    def add_product(product)
        @items << LineItem.for_product(product)
        @total_price += product.price
    end
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
    belongs_to :outfit
    def self.for_outfit(outfit)
        item = self.new
        item.quantity = 1
        item.outfit = outfit
        item.unit_price = outfit.price
        item
    end 
end

app/models/outfit.rb
class Outfit < ApplicationRecord 
    belongs_to :user 
    has_one_attached :picture
    
end 

app/models/user.rb
class User < ApplicationRecord 
     # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable

  validates :username, presence: true
  has_many :outfits
  has_many :wish_list_items

  
  
  def wish_list_outfits
    wish_list_items.map do |wl|
      wl.outfit
    end
  end

  
end

app/models/wish_list_item.rb
class WishListItem < ApplicationRecord
    belongs_to :user
    belongs_to :outfit
end 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!

end

app/controllers/outfits_controller.rb
class OutfitsController < ApplicationController 
    def index
        @outfits = Outfit.all 
    end 

    def new
        @outfit = Outfit.new
    end 

    def show 
        @outfit = Outfit.find(params[:id])
    end 

    def create
        @outfit = Outfit.new(outfit_params)
        @outfit.user_id = current_user.id
         if @outfit.save
            redirect_to @outfit 
            flash[:notice] = " New item added!"
         else 
            redirect_back(fallback_location: root_path)
            flash[:alert] = "Item creation failed"
         end
    end 

    def destroy
        outfit = Outfit.find(params[:id])
        if current_user == outfit.user
            outfit.destroy
            redirect_to "/outfits"
            flash[:notice] = "Item destroyed"
        else 
            redirect_back(fallback_location: root_path)
            flash[:alert] = "Not authorized to delete item"
        end 
    end 

    def update 
        outfit = Outfit.find(params[:id])
        if current_user == outfit.user
            outfit = Outfit.find(params[:id])
            outfit.update(outfit_params)
            redirect_to "/outfits" 
            flash[:notice] = "Update successful!"
        else 
            redirect_back(fallback_location: root_path)
            flash[:alert] = "Not authorized to edit item"
        end 
    end 

    def edit 
        @outfit = Outfit.find(params[:id])
        if current_user != @outfit.user
            redirect_back(fallback_location: root_path)
            flash[:alert] = "Not authorized to edit item"
        end 
    end 

    def wishlist
        @outfits = Outfit.where("wishlist = ?", true)
    end

    private 
    def outfit_params
        params.require(:outfit).permit(:size, :brand, :picture, :color, :price, :wishlist)
    end
    def edit_params
        params.require(:outfit).permit(:size, :price, :color)
    end
end 

app/controllers/store_controller.rb
class StoreController < ApplicationController
def add_to_cart
    outfit = outfit.find(params[:id])
    @cart = find_cart
    @cart.add_outfit(outfit)
    redirect_to(:action => 'display_cart')
end

def display_cart
    @cart = find_cart
    @items = @cart.items
end

private
def find_cart
session[:cart] ||= Cart.new
end
end 

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
   before_action :configure_sign_up_params, only: [:create]
   before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
   def configure_sign_up_params
     devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
   end

  # If you have extra params to permit, append them to the sanitizer.
   def configure_account_update_params
     devise_parameter_sanitizer.permit(:account_update, keys: [:username])
   end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController 
    def show
        @user = User.find(params[:id])
    end 
    
end 

app/controllers/wish_list_items_controller.rb
class WishListItemsController < ApplicationController
    before_action :find_outfit

    def create
        WishListItem.create(outfit: @outfit, user: current_user)

        redirect_to outfit_path(@outfit)
        flash[:notice]= "Add to wish list"
    end 

    private
    def find_outfit
        @outfit = Outfit.find(params[:outfit_id])
    end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Boutique</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans+Condensed:300&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="style2.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.min.css">
    <link rel="stylesheet" href="../styles/styles.css">
    <link href="https://fonts.googleapis.com/css?family=Chonburi&display=swap" rel="stylesheet">

  </head>

  <body class="bg-dark">
  <% if user_signed_in? %>
  <nav aria-label="breadcrumb ">
    <ol class="breadcrumb bg-dark">
      <li class="breadcrumb-item my-sm-2 font justify-content-end" aria-current="page">Logged in as <strong><%= current_user.username %></strong>.</li>
      <li class="breadcrumb-item my-sm-2 link"><%= link_to 'Edit profile', edit_user_registration_path%></li>
      <li class="breadcrumb-item my-sm-2 link"><%= link_to "Logout", destroy_user_session_path, method: :delete%></li>
      <li class="breadcrumb-item my-sm-2 link"><%= link_to "Home", outfits_path %></li>
      <li class="breadcrumb-item my-sm-2 link"><%= link_to "Wish List", wishlist_outfits_path %></li>
   
    </ol>
  </nav>
  <% else %>
    <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
    <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
  <% end %>

 

  <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>
            
</body>
<%= yield %>
</html>

app/views/outfits/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-4"></div>
    <div class="col-4">
      <%= form_with model: @outfit do |f| %>
          <div><%=image_tag(@outfit.picture, class: "my-pic")%></div>
          <div class="form-group">
              <label for="exampleFormControlSelect1">Size:</label>
              <select class="form-control" name="outfit[size]" id="exampleFormControlSelect1">
                <option>XS</option>
                <option>S</option>
                <option>M</option>
                <option>L</option>
                <option>XL</option>
              </select>
            </div>
            <div class="form-group">
              <label for="exampleFormControlTextarea1">Color:</label>
              <textarea class="form-control" name="outfit[color]" id="exampleFormControlTextarea1" rows="1"></textarea>
            </div>
            <div class="form-group">
              <label for="exampleFormControlTextarea1">Price:</label>
              <textarea class="form-control" name="outfit[price]" id="exampleFormControlTextarea1" rows="1"></textarea>
            </div>
            <%= f.submit %>    
      <% end %>
    </div>
  </div>
</div>

app/views/outfits/index.html.erb
<div class="jumbotron bg-dark">
<h1 class="title text-center">HAPPY SHOPPING!</h1>
</div>

<button type="button" class="btn btn-outline-success button link_2"><%= link_to "Add", new_outfit_path %> </button>

<div class = "container">
    <div class = "row">
          <% @outfits.each do |outfit| %>
            <div class="col-4">
              <div class="card my-card" style="width: 18rem; border-color: white;">
                <%= link_to(image_tag(outfit.picture, class: "my-pic"), outfit) %>
                <div class="card-body bg-dark">
                  <p class="card-text">
                  <p class="font">photo by: <%= link_to outfit.user.username, outfit.user, class:"font"%></p>
                </div>
              </div>
              </div>
          <% end %>
    </div>
</div>

app/views/outfits/new.html.erb
<div class="jumbotron jumbotron-fluid bg-dark">
<div class="container">
  <h1 class="display-4 title">ADD A NEW ITEM!</h1>
</div>
</div>

<div class="container">
  <div class="row">
    <div class="col-4"></div>
    <div class="col-4">
   
    <%= form_with model: @outfit do |f| %>

      <div class="form-group">
        <label for="exampleFormControlTextarea1" class="font">picture: <%= f.file_field :picture, required: true %></label>
        <textarea class="form-control" id="exampleFormControlTextarea1" rows="1" placeholder="Optional description"></textarea>
      </div>
      <div class="form-group">
        <label for="exampleFormControlSelect1" class="font">Size:</label>
        <select name="outfit[size]" class="form-control" id="exampleFormControlSelect1">
          <option>XS</option>
          <option>S</option>
          <option>M</option>
          <option>L</option>
          <option>XL</option>
        </select>
      </div>
      <div class="form-group">
        <label for="exampleFormControlTextarea1" class="font">Brand:</label>
        <textarea name="outfit[brand]" class="form-control" id="exampleFormControlTextarea1" rows="1"></textarea>
      </div>
      <div class="form-group">
        <label for="exampleFormControlTextarea1" class="font">Color:</label>
        <textarea name="outfit[color]" class="form-control" id="exampleFormControlTextarea1" rows="1"></textarea>
      </div>
      <div class="form-group">
        <label for="exampleFormControlTextarea1" class="font">Price:</label>
        <textarea name="outfit[price]" class="form-control" id="exampleFormControlTextarea1" rows="1"></textarea>
      </div>
      <%= f.submit %>    
      <% end %>
    </div>
  </div>
</div>

app/views/outfits/show.html.erb
<div class="jumbotron bg-dark">
  <h1 class="display-4 title text-center">DESCRIPTION</h1>
</div>

<div class="container">
  <div class="row">
    <div class="col-4">
    <div><%=image_tag(@outfit.picture, class: "my-pic")%></div>
    <% if current_user.wish_list_outfits.include? @outfit %>
      <p class = "margen font">Added to your wish list</p>
    <% else %>
      <p class = "margen"><%= button_to "Wish list", "/outfits/#{@outfit.id}/wish_list_items", method: :post, class: "btn btn-info"%></p>
    <% end %>

      <% if current_user == @outfit.user %>
        <p class = "margen"><%= button_to "Edit", "/outfits/#{@outfit.id}/edit", method: :get, class:"btn btn-warning"%></p>
        <p class = "margen"><%= button_to "Delete", @outfit, method: :delete, class: "btn btn-danger"%></p>
      <% end %>
    </div>

    <div class="col-4">
      <p class="font">Size: <%= @outfit.size %></p>
      <p class="font">Brand: <%= @outfit.brand %></p>
      <p class="font">Color: <%= @outfit.color %></p>
      <p class="font">Price: <%= @outfit.price %></p>
    </div>
  </div>
</div>

app/views/outfits/wishlist.html.erb
<div class="jumbotron bg-dark">
<h1 class="title text-center">WISH LIST!</h1>
</div>

<div class = "container">
    <div class = "row">
<% current_user.wish_list_outfits.each do |outfit| %>
    <div class="col-4">
        <div class="card my-card" style="width: 18rem; border-color: white;">
          <%= link_to(image_tag(outfit.picture, class: "my-pic"), outfit) %>
          <div class="card-body bg-dark">
            <p class="card-text">
            <p class="font">photo by: <%= link_to outfit.user.username, outfit.user, class:"font"%></p>
          </div>
        </div>
        </div>
<% end %>



<p class = "margen"> <%= link_to "back", outfits_path, class: "btn btn-info"%></p>

app/views/store/display_cart.html.erb
<h1>Cart</h1>
<p>You have <%= @items.size %>items in your cart.</p>

app/views/users/show.html.erb
<div class="jumbotron bg-dark">
<h1 class="title text-center">HAPPY SHOPPING!</h1>
</div>

<div class="container">
    <div class="row">
        <% @user.outfits.each do |outfit| %>
            <div class="col-4">
                <%= link_to(image_tag(outfit.picture, class: "my-pic"), "/outfit/#{outfit.id}") %>
                <p class="font">Size: <%= outfit.size %><p>
                <p class="font">Color: <%= outfit.color %><p>
                <p class="font">Price: <%= outfit.price %><p>
                <p class="font">Brand: <%= outfit.brand %><p>
            </div>
        <% end %>
    </div>
    </div>
</div>
    
    